config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash'
  
  devise_for :partners, controllers: { sessions: 'partners/sessions', registrations: 'partners/registrations' }
  
  resources :clients do
    collection do
      get :active
      get :archive
    end
  end  
  
  resources :invoices do
    collection do
      get :edit
      get :paid
      get :unpaid
      get :draft
    end
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
   has_many :services
   belongs_to :client

   accepts_nested_attributes_for :services
   
    scope :paid, ->{ where(status: "paid") }
    scope :unpaid, ->{ where(status: "unpaid") }   
    scope :draft, ->{ where(status: "draft") }    
end

app/controllers/invoice_controller.rb
class InvoicesController < ApplicationController
    before_action :authenticate_partner!
    before_action :set_invoice, only: [:edit, :update, :show, :destroy]
    
    def index
       @invoices = Invoice.all
       @services = Service.all
    end
    
    def new
       @invoice = Invoice.new
    end
    
    def create
       @invoice = Invoice.new(invoice_params)
       @invoice = client.invoices.build
        if @invoice.save
            flash[:notice] = "Successfully saved invoice!"
            redirect_to invoices_path
        else
            render 'new'
        end
    end
    
    def show
    end
    
    def edit
    end    
    
    def update
        if @invoice.update(invoice_params)
            flash[:notice] = "Successfully saved invoice!"
            redirect_to invoices_path
        else
            render 'edit'
        end        
    end
    
    def destroy
        if @invoice.present?
            @invoice.destroy
            flash[:notice] = "Successfully removed invoice!"
            redirect_to invoices_path
        else
            flash[:notice] = "Error removing invoice!"
            redirect_to invoices_path
        end
    end
    
   private
    
    def set_invoice
        @invoice = Invoice.find(params[:id])
    end
    
    def invoice_params
       params.require(:invoice).permit(:invoice_number, :invoice_date, :due_date, :total_amount, :invoice_note, services_attributes: [:name, :baserate, :amount, :_destroy]) 
    end    
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    before_action :authenticate_partner!
    before_action :set_invoice, only: [:edit, :update, :show, :destroy]
    
    def index
        @invoices = Invoice.all
    end
    
    def unpaid
       @invoice = Invoice.unpaid
       render action: :index
    end
    
    def paid
       @invoice = Invoice.paid
       render action: :index
    end    
    
    def draft
        @invoice = Invoice.draft                    
        render action: :index
    end
    
    def new
       @invoice = Invoice.new
    end
    
    def create
       @invoice = client.invoices.build(invoice_params)
        if @invoice.save
            # format.js - links to create.js.erb
            # format.html - links to create => new.html.erb
            # format.json
            
            
            flash[:notice] = "Successfully saved invoice!"
            redirect_to invoices_path
        else
            render 'new'
        end
    end
    
    def show
    end
    
    def edit
    end    
    
    def update
        if @invoice.update(invoice_params)
            flash[:notice] = "Successfully saved invoice!"
            redirect_to invoices_path
        else
            render 'edit'
        end        
    end
    
    def destroy
        if @invoice.present?
            @invoice.destroy
            flash[:notice] = "Successfully removed invoice!"
            redirect_to invoices_path
        else
            flash[:notice] = "Error removing invoice!"
            redirect_to invoices_path
        end
    end
    
    private
    
    def set_invoice
        @invoice = Invoice.find_by(params[:client_id])
    end
    
    def invoice_params
       params.require(:invoice).permit(:invoice_number, :invoice_date, :due_date, :total_amount, :invoice_note, services_attributes: [:name, :baserate]) 
    end    
end

app/helpers/invoice_helper.rb
module InvoiceHelper
 def no_invoice
    if @invoices.exists?
        render partial: "invoices/invoicelist"
    else
        render partial: "invoices/no_invoices"
    end
 end
end

app/views/invoices/_form.html.erb
<% if @invoice.errors.any? %>
    <p>The following errors prevented your invoice from saving:</p>
    
    <ul>
        <% @invoice.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    
<% end %>
    
<%= form_for @invoice, url: clients_path(@invoice), html: { class: "form-group" } do |f| %>
    <p>
        <%= f.label "Invoice Number" %>
        <%= f.text_field :invoice_number, class: "form-control" %>
    </p>
    
    <p>
        <%= f.label "Invoice Date" %>
        <%= f.text_field :invoice_date, class: "form-control", data:{ provide:'datepicker' }  %>
    </p>
    
    <p>
        <%= f.label "Due Date" %>
        <%= f.text_field :due_date, class: "form-control", data:{ provide:'datepicker' }  %>
    </p>
    
    <p>
        <%= f.label "Total Amount" %>
        <%= f.text_field :total_amount, class: "form-control" %> 
    </p>
    
    <p>
        <%= f.label "Invoice Note" %>
        <%= f.text_field :invoice_note, class: "form-control" %> 
    </p>    
    
    <p>
        <%= f.hidden_field :status, :value => "draft" %>
    </p>
    
        <%= fields_for :services do |service_form| %>
            <p>
                <%= service_form.label "Select Service" %>
                <%= service_form.collection_select :name, Service.order(:name), :id, :name, { :include_blank => "Add services" }, class: "form-control"  %>
            </p>  
        <% end %>
    <p>
        <%= f.submit "Save", class: " btn btn-warning form-control" %>
    </p>
    
<% end %>

app/views/invoices/_invoicelist.html.erb
<table class="table">
    <tbody>
        <% @invoices.each do |invoice| %>    
        <tr class= "clientcard" data-href="<% link_to edit_invoice_path(invoice.client, invoice) %>" data-remote="true">
          <td><p><strong><%= invoice.client.name %></strong></p></td>
          <td class="text-muted"><strong><%= invoice.due_date %></strong></td>
          <td><%= invoice.invoice_number %></td>
          <td><%= number_to_currency(invoice.total_amount, precision: 2) %></td>
          <td><%= link_to "Edit", edit_invoice_path(invoice), class: "btn btn-sm btn-warning" %></td>
        </tr>
        <% end %>            
    </tbody>
</table>

app/views/invoices/_no_invoices.html.erb
<p>
    You have no invoices added to your account.
</p>

app/views/invoices/_no_paid.html.erb
<p>
    You have no invoices added to your account.
</p>

app/views/invoices/edit.html.erb
<div class="container">
    <%= render "invoices/form" %>
    
    <p>
        <%= link_to "Edit this invoice", edit_invoice_path(@invoice) %> | <%= link_to "Back to invoices", clients_path %>    
    </p>
</div>

app/views/invoices/index.html.erb
<%= render "layouts/sidebar" %>

<div class="container-fluid">
    <div class="row rightbar">
        <div class="col-lg-5 list-container">
            <div class="list-content">
                <div class="list-title">
                    <h2>
                        Invoices
                    </h2>
                </div>
                
            
                <div class="listings">
                    <div class="tabswrapper">
                        <div class="tablist">
                            <%= link_to "All", invoices_path, class: "space" %>
                            <%= link_to "Unpaid", unpaid_invoices_path, class: "space" %>
                            <%= link_to "Paid", paid_invoices_path, class: "space" %>
                            <%= link_to "Draft", draft_invoices_path, class: "space" %>
                        </div>
                    </div>
                    
                    <div class="contactcards">
                        <div class="ccards-list">
                            <div class="cardsgroup">
                                <div>
                                   <%= no_invoice %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <%= render "layouts/projection" %>
        
    </div>
</div>

app/views/invoices/new.html.erb
<div class="container">
    <%= render "invoices/form" %>
    
    <p>
        <%= link_to "Back to invoices", invoices_path, class: "btn btn-dark" %>    
    </p>
</div>

app/views/invoices/show.html.erb
<div class="container invoice-wrapper">
    <div class="row invoice-spacer">
        <div class="invoice-left col-lg-6">
            <div class="invoice-header">
                <%= link_to "Edit", edit_invoice_path(@invoice), class: "btn btn-sm btn-warning space" %>     <%= link_to "Delete", invoice_path(@invoice), method: :delete, data: {confirm: "Are you sure you want to delete this invoice? This cannot be undone."}, class: "btn btn-sm btn-secondary space" %>     <%= link_to "Back to invoices", invoices_path, class: "btn btn-sm btn-dark space" %>
                
                <div class="invoice-spacer"></div>
                
                <strong><%= @invoice.client.name %></strong>

                <div class="invoice-spacer"></div>

                <small class="text-muted">Invoice Number: <%= @invoice.invoice_number %></small>
            </div>
            
            <div class="invoice-content">
                <strong>Invoice Details</strong>
                
                <div class="invoice-spacer"></div>
                
                <ul class="list-unstyled">
                    <li class="text-muted"><strong>Client</strong></li>
                    <li><%= @invoice.client.name %></li>
                    <li class="invoice-spacer"></li>
                    <li class="text-muted"><strong>Invoice Amount</strong></li>
                    <li><%= number_to_currency(@invoice.total_amount, precision: 2) %></li>
                    <li class="invoice-spacer"></li>
                    <li class="text-muted"><strong>Invoice Number</strong></li>
                    <li><%= @invoice.invoice_number %></li>
                    <li class="invoice-spacer"></li>
                    <li class="text-muted"><strong>Invoice Date</strong></li>
                    <li><%= @invoice.invoice_date %></li>
                    <li class="invoice-spacer"></li>
                    <li class="text-muted"><strong>Due Date</strong></li>
                    <li>Due Date: <%= @invoice.due_date %></li>
                    <li class="invoice-spacer"></li>
                    <li class="text-muted"><strong>Services</strong></li>
                </ul>        
            </div>
            <div class="invoice-footer">
                <p class="h3 text-muted text-left">Total</p>
            </div>
        </div>
        <div class="invoice-right col-lg-6">
            <div class="invoice-header">
                <%= link_to "Pay Invoice", invoices_path, class: "btn btn-sm btn-success" %>    
            </div>
            
            <div class="invoice-footer">
                <p class="h2">
                    <%= number_to_currency(@invoice.total_amount, precision: 2) %>
                </p>                
            </div>
        </div>
    </div>   
</div>

app/views/invoices/show.js.erb
$('#projection').click(function() {
    window.location = $(this).data("href");
    }