config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash'
  
  devise_for :partners, controllers: { sessions: 'partners/sessions', registrations: 'partners/registrations' }
  
  resources :clients do
    collection do
      get :active
      get :archive
    end
  end  
  
  resources :invoices do
    collection do
      get :edit
      get :paid
      get :unpaid
      get :draft
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
    belongs_to :partner
    has_many :invoices
    
    accepts_nested_attributes_for :invoices
    
    scope :all_clients, ->{ where(status: "current").or where(status: "archive").or where(status: nil) }
    scope :active, ->{ where(status: "current") }
    scope :archive, ->{ where(status: "archive") }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController 
    before_action :authenticate_partner!
    before_action :mark_clients, only: [:index, :active, :archive]
    before_action :set_client, only: [:edit, :update, :show, :destroy]

    def index
        if @clients.exists?
          render action: :index
        else
          flash[:notice] = "You have no clients added to your account. Please add your first client!"
          redirect_to new_client_path
        end
    end
    
    def active
        @client = Client.active
        if @client.exists?
          render action: :index
        else
          flash[:notice] = "You have no active clients. Please add new clients!"
          redirect_to new_client_path  
        end
    end
    
    def archive
        @client = Client.archive
        if @client.exists?
          render action: :index
        else
          flash[:notice] = "You have no clients archived!"
          redirect_to clients_path  
        end
    end
        
    def new
       @client = Client.new
    end
    
    def create
       @partner = current_partner
       @client = @partner.clients.build(client_params)
        if @client.save
            format.js
            format.html { redirect_to @client, notice: 'Successfully saved client!' }
            format.json { render :show, status: :created, location: @client }
        else
            format.html { render :new }
            format.json { render :json, @client.errors, status: :unprocessable_entity }
        end
    end
    
    def show
    end
    
    def edit
    end    
    
    def update
        if @client.update(client_params)
            flash[:notice] = "Successfully saved client!"
            redirect_to clients_path
        else
            render 'edit'
        end        
        
    end
    
    def destroy
        if @client.destroy && @client.present?
            flash[:notice] = "Client was removed!"
            redirect_to clients_path
        else
            flash[:notice] = "Client no longer exists! May have been deleted already."
            redirect_to clients_path
        end
    end
    
    private
    
    def mark_clients
       @clients = current_partner.clients
    end
    
    def set_client
        @client = Client.find(params[:id])
    end
    
    def client_params
       params.require(:client).permit(:name, :client_type, :poc_name, :poc_email, :poc_number, :status, :first_name, :last_name)
    end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/_form.html.erb
<% if @client.errors.any? %>
    <p>The following errors prevented your client from saving:</p>
    
    <ul>
        <% @client.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    
<% end %>
    
<%= form_for @client, html: { class: "form-group" } do |f| %>
    <p>
        <%= f.label "Client Name" %>
        <%= f.text_field :name, class: "form-control" %>
    </p>
    
    <p>
        <%= f.label "Client Type" %>
        <%= f.select :client_type, options_for_select([['Candidate', 'Candidate'], ['Political Action Committee', 'Political Action Committee'], ['501c4', '501c4']]), { :include_blank => "Please select category"}, class: "form-control"  %>
    
    </p>
    
    <p>
        <%= f.label "Primary Contact Name" %>
        <%= f.text_field :poc_name, class: "form-control" %>
    </p>
    
    <p>
        <%= f.label "Primary Contact Email" %>
        <%= f.text_field :poc_email, class: "form-control" %>
    </p>
    
    <p>
        <%= f.label "Primary Contact Phone" %>
        <%= f.text_field :poc_number, class: "form-control" %> 
    </p>
    
    <p>
        <%= f.hidden_field :status, :value => "current" %>
    </p>
    
    <p>
        <%= f.submit "Save", class: " btn btn-warning form-control" %>
    </p>
    
<% end %>

app/views/clients/create.js.erb
$('#addclient form').remove();
$('#showclient').show();
$('table#allclients tbody').append("<%= j render @client %>")

app/views/clients/edit.html.erb
<div class="container">
    <%= render "clients/form" %>

    <p>
        <%= link_to "Back to Clients", clients_path, class: "btn btn-dark" %>    
    </p>
</div>

app/views/clients/index.html.erb
<%= render "layouts/sidebar" %>

<div class="container-fluid">
    <div class="row rightbar">
        <div class="col-lg-5 list-container">
            <div class="list-content">
                <div class="list-title">
                    <h2>
                        Clients
                    </h2>
                </div>
                
                <div class="listings">
                    <div class="tabswrapper">
                        <div class="tablist">
                            <%= link_to "All", clients_path, class: "space" %>
                            <%= link_to "Existing", active_clients_path, class: "space" %>
                            <%= link_to "Archive", archive_clients_path, class: "space" %>
                        </div>
                    </div>
                    
                    <div class="contactcards">
                        <div class="ccards-list">
                            <div class="cardsgroup">
                                <table class="table" id="allclients">
                                    <tbody>
                                        <% @clients.each do |client| %>
                                        <tr class= "clientcard" data-link="<%= edit_client_path(client) %>">
                                            <td class= "clientname"><%= client.name %></td>    
                                            <td class= "poc"><%= client.poc_number %></td>
                                            <td class= "poc"><%= client.poc_email %></td>
                                        </tr>
                                        <% end %>            
                                    </tbody>
                                </table>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <%= render "layouts/projection" %>
        
    </div>
</div>

app/views/clients/new.html.erb
<div class="container" id="addclient">
    <%= render "clients/form" %>

    <p>
        <%= link_to "Back to Clients", clients_path, class: "btn btn-dark" %>    
    </p>
</div>

app/views/clients/new.js.erb
var projection = document.querySelector("#projection")

projection.innerHTML = <%= j render partial: 'clients/form' %>

app/views/clients/show.html.erb
<div class="container" id="showclient">
    <div class="row">
        <%= render "layouts/navigation" %>
        <p class="space"><%= create_invoice %></p>   
        <p class="space"><%= view_invoice %></p> 
    </div>
    
    <ul class="list-group">
        <li class="list-group-item">Client name: <%= @client.name %></li>
        <li class="list-group-item">Client type: <%= @client.client_type %></li>
        <li class="list-group-item">Primary Contact Name: <%= @client.poc_name %></li>
        <li class="list-group-item">Primary Contact Email: <%= @client.poc_email %></li>
        <li class="list-group-item">Primary Contact Phone: <%= @client.poc_number %></li>
    </ul>
    
    <p>
        <%= link_to "Edit this client", edit_client_path(@client), class: "btn btn-secondary" %> | <%= link_to "Back to clients", clients_path, class: "btn btn-dark" %>    
    </p>
</div>