config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash'
  
  devise_for :partners, controllers: { sessions: 'partners/sessions', registrations: 'partners/registrations' }
  
  resources :clients do
    collection do
      get :active
      get :archive
    end
  end  
  
  resources :invoices do
    collection do
      get :edit
      get :paid
      get :unpaid
      get :draft
    end
  end
end

app/views/pages/index.html.erb
<div class="container">
    <div class="row mt-2">
        <div class="col-lg">
            <%= image_tag "logo.png", :size => '48x48' %>
            <h2 class="pt-5">Ballot America Partners</h2>     
        </div>
        
        <div class="col-lg-2">
                <%= link_to "Login", new_partner_session_path, class: "btn btn-primary" %>
        </div>
        
    </div>
    
    
    <div class="row">
        <div class="col-lg"> <!-- Content Left  -->
            <%= link_to "Become a partner", new_partner_registration_path, class: "btn btn-info" %>
        </div>
        
        <div class="col-lg"><!-- Content Right -->
            
        </div>         
    </div>
    
    <div class="row">
    </div>
</div>

app/views/pages/splash.html.erb
<div class="container">
    <div class="row mt-5">
        <div class="col-lg">
            <%= image_tag "logo.png", :size => '48x48' %>
            <h2 class="pt-5">Ballot America Partners</h2>     
        </div>
        
        <div class="col-lg-2">
            <%= link_to "Login", new_partner_session_path, class: "btn btn-primary" %>
        </div>
        
    </div>
    
    
    <div class="row">
        <div class="col-lg"> <!-- Content Left  -->
            <%= link_to "Become a partner", new_partner_registration_path, class: "btn btn-info" %>
        </div>
        
        <div class="col-lg"><!-- Content Right -->
            
        </div>          
    </div>    
</div>