config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash'
  
  devise_for :partners, controllers: { sessions: 'partners/sessions', registrations: 'partners/registrations' }
  
  resources :clients do
    collection do
      get :active
      get :archive
    end
  end  
  
  resources :invoices do
    collection do
      get :edit
      get :paid
      get :unpaid
      get :draft
    end
  end
end

app/views/layouts/_navigation.html.erb
<div class="container">
    <div class="row">
        <p class="space">
           <%= link_to "Add a Client", new_client_path, class: "btn btn-sm btn-success" %>
        </p>  

        <p class="space">
            <%= link_to "Back to Clients", clients_path, class: "btn btn-sm btn-primary" %>
        </p>

        <p class="space">
            <%= link_to "Sign Out", destroy_partner_session_path, method: :delete, class: "btn btn-sm btn-danger" %>
        </p>
    </div>
</div>

app/views/layouts/_projection.html.erb
<div class="col-lg-7 projection-container">
    <div id="projection">
        
    </div>
</div>  

app/views/layouts/_sidebar.html.erb
<!--div class="sticky"-->    
    <div class="row toptobottom">
        <div class="col-lg-auto menu-container" id="leftbar">
            <div class="menutop">
                <div class="logo-container pt-3">
                    <%= image_tag "logo.png", size: "48x48" %>
                </div>

                <div class="spacer"></div>
                <div class="spacer"></div>                
                
                <div class="row icon-nav dropright">
                    <div data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%=  link_to icon('fas', 'plus-square'), new_client_path, :size => "128x128", class: "icon-button" %>
                    </div>
                    <ul class="dropdown-menu">
                        <li class="list-group-item"><%=  link_to "Client", new_client_path, remote: true %></li>
                        <li class="list-group-item"><%=  link_to "Invoice", new_invoice_path %></li>
                    </ul>
                </div>

                <div class="spacer"></div>
                <div class="spacer"></div>                
                <div class="spacer"></div>                 
                
                <div class="row icon-nav">
                    <%= link_to icon('fas', 'address-book'), clients_path, :size => "64x64", class: "icon-links" %>
                    <div class="icon-text">Clients</div>
                </div>
                <div class="row icon-nav">
                    <%= link_to icon('fas', 'file-invoice'), invoices_path, :size => "64x64", class: "icon-links" %>  
                    <div class="icon-text">Invoices</div>
                </div>            
                <div class="row icon-nav">
                    <%= link_to icon('fas', 'cog'), clients_path, :size => "64x64", class: "icon-links" %>  
                    <div class="icon-text">Settings</div>
                </div>           
            </div>
    
            <div class="menubottom">
                <div class="userbadge-container dropright">
                    <div class="badgename" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= name_initials %>
                    </div>
                    <ul class="dropdown-menu">
                        <li class="list-group-item"><span>Settings</span><%#= link_to "Settings", account_settings_path %></li>
                        <li class="list-group-item"><%= link_to "Logout", destroy_partner_session_path, method: :delete %></li>
                    </ul>
                </div>
            </div>
        </div>        
    </div>
<!--/div-->    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballot America Partners</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
        <!-- Flash messages -->
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>  
          
    <div class="container-fluid app-container">
      <div class="row layout">          
          <!-- Site content -->
          <%= yield %>
      </div>
    </div>  
    
  </body>
</html>